"""add_Alarm_create_at

Revision ID: 2d8c77ad03ba
Revises: 98df86f52a71
Create Date: 2024-07-22 04:36:42.825222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2d8c77ad03ba'
down_revision: Union[str, None] = '98df86f52a71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alarm', 'type',
               existing_type=mysql.TINYINT(unsigned=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alarm', 'type',
               existing_type=mysql.TINYINT(unsigned=True),
               nullable=False)
    # ### end Alembic commands ###
