"""empty message

Revision ID: 34050c825637
Revises: eb8d938396a3
Create Date: 2024-08-03 23:51:03.519965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '34050c825637'
down_revision: Union[str, None] = 'eb8d938396a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'create_at',
               existing_type=mysql.TIMESTAMP(fsp=3),
               nullable=False)
    op.drop_index('idx_post_create_at', table_name='post')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_post_create_at', 'post', ['create_at'], unique=False)
    op.alter_column('post', 'create_at',
               existing_type=mysql.TIMESTAMP(fsp=3),
               nullable=True)
    # ### end Alembic commands ###
