"""add_Resume_updated_at

Revision ID: 3d25789029dc
Revises: e3f6e6f6b104
Create Date: 2024-07-22 02:58:26.616243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3d25789029dc'
down_revision: Union[str, None] = 'e3f6e6f6b104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('update_at', mysql.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'update_at')
    # ### end Alembic commands ###
