"""Add index to create_at in posts

Revision ID: 57f6365531e0
Revises: 5c4c5d749f55
Create Date: 2024-08-03 21:33:25.520594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57f6365531e0'
down_revision: Union[str, None] = '5c4c5d749f55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_post_create_at', 'post', ['create_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_post_create_at', table_name='post')
    # ### end Alembic commands ###
