"""change_ACTIVE_to_ONGOING

Revision ID: 5c4c5d749f55
Revises: 10c8f21e8a54
Create Date: 2024-07-27 05:20:42.918432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c4c5d749f55'
down_revision: Union[str, None] = '10c8f21e8a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
