"""add index to create_at in posts

Revision ID: 9462c2f089aa
Revises: 34050c825637
Create Date: 2024-08-03 23:53:51.199769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9462c2f089aa'
down_revision: Union[str, None] = '34050c825637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_post_create_at', 'post', ['create_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_post_create_at', table_name='post')
    # ### end Alembic commands ###
