"""add_Alarm_create_at

Revision ID: 98df86f52a71
Revises: 3d25789029dc
Create Date: 2024-07-22 04:34:22.637938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '98df86f52a71'
down_revision: Union[str, None] = '3d25789029dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm', sa.Column('create_at', mysql.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alarm', 'create_at')
    # ### end Alembic commands ###
