"""설명 메시지

Revision ID: 9a2aebfd2ba2
Revises: fdd25451957a
Create Date: 2024-07-20 16:10:08.413707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9a2aebfd2ba2'
down_revision: Union[str, None] = 'fdd25451957a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MemberTag',
    sa.Column('tag_id', sa.BIGINT(), nullable=False),
    sa.Column('member_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'member_id')
    )
    op.create_table('PostTag',
    sa.Column('tag_id', sa.BIGINT(), nullable=False),
    sa.Column('post_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'post_id')
    )
    op.create_table('ResumeTag',
    sa.Column('tag_id', sa.BIGINT(), nullable=False),
    sa.Column('resume_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'resume_id')
    )
    op.drop_table('posttag')
    op.drop_table('resumetag')
    op.drop_table('membertag')
    op.add_column('tag', sa.Column('category_key', sa.BIGINT(), nullable=False))
    op.create_foreign_key(None, 'tag', 'category', ['category_key'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_column('tag', 'category_key')
    op.create_table('membertag',
    sa.Column('tag_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('member_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], name='membertag_ibfk_1'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='membertag_ibfk_2'),
    sa.PrimaryKeyConstraint('tag_id', 'member_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('resumetag',
    sa.Column('tag_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('resume_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], name='resumetag_ibfk_1'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='resumetag_ibfk_2'),
    sa.PrimaryKeyConstraint('tag_id', 'resume_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('posttag',
    sa.Column('tag_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('post_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='posttag_ibfk_1'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='posttag_ibfk_2'),
    sa.PrimaryKeyConstraint('tag_id', 'post_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('ResumeTag')
    op.drop_table('PostTag')
    op.drop_table('MemberTag')
    # ### end Alembic commands ###
