"""delete_Alarm_contents

Revision ID: b3b50ddd8c75
Revises: 2d8c77ad03ba
Create Date: 2024-07-22 05:03:46.866686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b3b50ddd8c75'
down_revision: Union[str, None] = '2d8c77ad03ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alarm', 'contents')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm', sa.Column('contents', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
