"""Resync database state

Revision ID: bdf266bdcc71
Revises: 9c40e60c8b92
Create Date: 2024-07-20 20:31:56.961207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdf266bdcc71'
down_revision: Union[str, None] = '9c40e60c8b92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_tag',
    sa.Column('tag_id', sa.BIGINT(), nullable=False),
    sa.Column('member_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'member_id')
    )
    op.create_table('post_tag',
    sa.Column('tag_id', sa.BIGINT(), nullable=False),
    sa.Column('post_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'post_id')
    )
    op.create_table('resume_tag',
    sa.Column('tag_id', sa.BIGINT(), nullable=False),
    sa.Column('resume_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'resume_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_tag')
    op.drop_table('post_tag')
    op.drop_table('member_tag')
    # ### end Alembic commands ###
