"""delete_Post_categoty_key_Tag_use_count

Revision ID: e3f6e6f6b104
Revises: 399cfea32828
Create Date: 2024-07-21 17:38:10.553462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e3f6e6f6b104'
down_revision: Union[str, None] = '399cfea32828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_ibfk_2', 'post', type_='foreignkey')
    op.drop_column('post', 'category_id')
    op.drop_column('tag', 'use_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('use_count', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('post', sa.Column('category_id', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key('post_ibfk_2', 'post', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###
