"""Initialize nkmemo entity..

Revision ID: fdd25451957a
Revises: 142b3c5c6721
Create Date: 2024-07-06 23:19:06.647484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fdd25451957a'
down_revision: Union[str, None] = '142b3c5c6721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('provider_type', sa.String(length=30), nullable=False),
    sa.Column('nickname', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('MemberTag',
    sa.Column('tag_id', sa.BIGINT(), nullable=False),
    sa.Column('member_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'member_id')
    )
    op.create_table('post',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.BIGINT(), nullable=False),
    sa.Column('category_id', sa.BIGINT(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('contents', sa.String(length=5000), nullable=False),
    sa.Column('create_at', mysql.TIMESTAMP(), nullable=False),
    sa.Column('update_at', mysql.TIMESTAMP(), nullable=False),
    sa.Column('deadline', mysql.TIMESTAMP(), nullable=False),
    sa.Column('max_member', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('view_count', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('like_count', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('current_member', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.BIGINT(), nullable=False),
    sa.Column('contents', sa.String(length=5000), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PostTag',
    sa.Column('tag_id', sa.BIGINT(), nullable=False),
    sa.Column('post_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'post_id')
    )
    op.create_table('ResumeTag',
    sa.Column('tag_id', sa.BIGINT(), nullable=False),
    sa.Column('resume_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'resume_id')
    )
    op.create_table('alarm',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.BIGINT(), nullable=False),
    sa.Column('receiver_id', sa.BIGINT(), nullable=False),
    sa.Column('post_id', sa.BIGINT(), nullable=False),
    sa.Column('type', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('contents', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatroom',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('parent_id', sa.BIGINT(), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('create_at', mysql.TIMESTAMP(), nullable=False),
    sa.Column('update_at', mysql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('like',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_chatroom',
    sa.Column('chatroom_id', sa.BIGINT(), nullable=False),
    sa.Column('member_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['chatroom_id'], ['chatroom.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('chatroom_id', 'member_id')
    )
    op.create_table('message',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('chatroom_id', sa.BIGINT(), nullable=False),
    sa.Column('member_id', sa.BIGINT(), nullable=False),
    sa.Column('contents', sa.String(length=255), nullable=False),
    sa.Column('create_at', mysql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['chatroom_id'], ['chatroom.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('member_chatroom')
    op.drop_table('like')
    op.drop_table('comment')
    op.drop_table('chatroom')
    op.drop_table('alarm')
    op.drop_table('ResumeTag')
    op.drop_table('PostTag')
    op.drop_table('resume')
    op.drop_table('post')
    op.drop_table('MemberTag')
    op.drop_table('tag')
    op.drop_table('member')
    op.drop_table('category')
    # ### end Alembic commands ###
